# Generated by Django 5.2.11 on 2026-03-27 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='definition',
            name='termId',
        ),
        migrations.AlterField(
            model_name='symptom',
            name='termId',
            field=models.ManyToManyField(blank=True, null=True, to='core.medicalterms'),
        ),
        migrations.AddField(
            model_name='definition',
            name='termId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='core.medicalterms'),
        ),
    ]
