# Generated by Django 5.2.11 on 2026-03-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_medicalterms_searchhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_name', models.CharField(max_length=255)),
                ('termId', models.ManyToManyField(to='core.medicalterms')),
            ],
        ),
    ]
