# Generated by Django 5.2.11 on 2026-03-28 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_definition_termid_alter_symptom_termid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='termId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.medicalterms'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='termId',
            field=models.ManyToManyField(to='core.medicalterms'),
        ),
    ]
