# Generated by Django 5.2.11 on 2026-04-09 08:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_definition_termid_alter_symptom_termid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='termId',
        ),
        migrations.RemoveField(
            model_name='medicalterms',
            name='term',
        ),
        migrations.AddField(
            model_name='medicalterms',
            name='cui',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='medicalterms',
            name='full_term',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='medicalterms',
            name='term_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='medicalterms',
            name='user_term',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='search_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Definition',
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
    ]
